version: '3.9'

networks:
  deploy-guide-dev:
    driver: bridge

services:
  user-db-service:
    image: postgres:13.3
    container_name: UserDBService
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    networks:
      - deploy-guide-dev      

  userservice.api:
    image: user-service-api
    container_name: user-service-api
    build:
      context: .
      dockerfile: UserService.API/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - deploy-guide-dev
    depends_on:
      - user-db-service