version: '3.9'

services:
  userdbservice:
    image: postgres:13.3
    container_name: UserDBService
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"

  userservice.api:
    image: userserviceapi
    container_name: UserService.API
    # environment:
    #   - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: UserService.API/Dockerfile
    ports:
      - "5000:80"